import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import request from 'supertest';
import {newDb} from 'pg-mem';
import {readFile} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {pool} from './db.js';
import {service,passwordHash} from './service.js';
test('private invitations bind workspace/email/role, require identity, expire, revoke, consume once and permit access removal',async t=>{
 if(process.env.TEST_REAL_DATABASE==='true')t.after(()=>pool.end());
 else{const memory=newDb();memory.public.none('CREATE TABLE tenants(id UUID PRIMARY KEY,name TEXT,slug TEXT UNIQUE)');memory.public.none(await readFile(new URL('../db/service.sql',import.meta.url),'utf8'));const db=new (memory.adapters.createPg().Pool)();pool.query=db.query.bind(db);pool.connect=db.connect.bind(db);}
 const app=express();app.use(express.json());app.use('/api',service);app.use((e,_req,res,_next)=>res.status(e.status||500).json({error:e.message}));
 const admin=randomUUID(),one=randomUUID(),two=randomUUID(),suffix=randomUUID();
 await pool.query('INSERT INTO tenants(id,name,slug) VALUES($1,$2,$3),($4,$5,$6)',[one,'Invited client',suffix,two,'Other client',suffix+'-other']);
 const email='admin-'+suffix+'@example.com';await pool.query('INSERT INTO service_users VALUES($1,$2,$3,$4)',[admin,email,passwordHash('IndividualPassword123!'),'Admin']);await pool.query("INSERT INTO service_memberships VALUES($1,$2,'admin')",[admin,one]);
 const agent=request.agent(app);await agent.post('/api/login').send({email,password:'IndividualPassword123!'}).expect(200);
 const outsider=request.agent(app);await outsider.get('/api/workspaces/'+one+'/records').expect(401);
 const target='client-'+suffix+'@example.com';
 const invitation=(await agent.post('/api/workspaces/'+one+'/invitations').send({email:target,name:'Client person',role:'client'}).expect(201)).body;
 const token=invitation.url.split('/invite/')[1];
 const stored=(await pool.query('SELECT token_hash FROM service_invitations WHERE id=$1',[invitation.id])).rows[0];assert.notEqual(stored.token_hash,token);
 await outsider.post('/api/invitation/accept').send({token,email:'wrong@example.com',password:'IndividualPassword123!'}).expect(400);
 await outsider.post('/api/invitation/accept').send({token,email:target,password:'IndividualPassword123!'}).expect(200);
 await outsider.post('/api/invitation/accept').send({token,email:target,password:'IndividualPassword123!'}).expect(400);
 await outsider.post('/api/login').send({email:target,password:'IndividualPassword123!'}).expect(200);
 await outsider.get('/api/workspaces/'+one+'/records').expect(200);await outsider.get('/api/workspaces/'+two+'/records').expect(403);
 await pool.query('INSERT INTO service_programs(tenant_id,profile) VALUES($1,$2)',[one,{aiGuideEnabled:true}]);
 await outsider.patch('/api/workspaces/'+one+'/portal/ai-settings').send({mode:'economy'}).expect(403);
 await agent.patch('/api/workspaces/'+one+'/portal/ai-settings').send({mode:'economy'}).expect(200);
 await agent.patch('/api/workspaces/'+one+'/portal/ai-settings').send({mode:'arbitrary-expensive-model'}).expect(400);
 const profile=(await pool.query('SELECT profile FROM service_programs WHERE tenant_id=$1',[one])).rows[0].profile;
 assert.equal(profile.aiGuideMode,'economy');assert.equal(profile.aiGuideEnabled,true);
 await outsider.post('/api/workspaces/'+one+'/invitations').send({email:'forbidden@example.com',name:'No',role:'admin'}).expect(403);
 const user=(await pool.query('SELECT id FROM service_users WHERE email=$1',[target])).rows[0];
 await agent.delete('/api/workspaces/'+one+'/members/'+user.id).expect(200);await outsider.get('/api/workspaces/'+one+'/records').expect(403);
 const second=(await agent.post('/api/workspaces/'+one+'/invitations').send({email:target,name:'Client person',role:'employee'}).expect(201)).body;
 const token2=second.url.split('/invite/')[1];
 await request(app).post('/api/invitation/accept').send({token:token2,email:target,password:'WrongPassword123!'}).expect(401);
 // Existing authenticated recipient can accept without changing their SSO/local password.
 await outsider.post('/api/invitation/accept').send({token:token2,email:target}).expect(200);
 const cancelled=(await agent.post('/api/workspaces/'+one+'/invitations').send({email:'cancel-'+target,name:'Cancel',role:'auditor'}).expect(201)).body;
 await agent.post('/api/workspaces/'+one+'/invitations/'+cancelled.id+'/revoke').send({}).expect(200);
 await request(app).post('/api/invitation/inspect').send({token:cancelled.url.split('/invite/')[1]}).expect(400);
 const expired=(await agent.post('/api/workspaces/'+one+'/invitations').send({email:'expire-'+target,name:'Expired',role:'auditor'}).expect(201)).body;
 await pool.query('UPDATE service_invitations SET expires_at=$1 WHERE id=$2',['2000-01-01',expired.id]);
 await request(app).post('/api/invitation/accept').send({token:expired.url.split('/invite/')[1],email:'expire-'+target,password:'IndividualPassword123!'}).expect(400);
 const other=(await agent.post('/api/workspaces/'+one+'/invitations').send({email:'other-'+target,name:'Other',role:'auditor'}).expect(201)).body;
 await agent.post('/api/workspaces/'+two+'/invitations/'+other.id+'/revoke').send({}).expect(403);
 await agent.post('/api/workspaces/'+one+'/invitations').send({email:'bad-'+target,name:'No',role:'admin'}).expect(400);
});
