// Short navigation labels, not reproduced normative standard text.
const groups = {
  5: [
    "Security policies",
    "Security responsibilities",
    "Separation of duties",
    "Management accountability",
    "Authority contacts",
    "Professional security contacts",
    "Threat intelligence",
    "Project security",
    "Asset inventory",
    "Acceptable use",
    "Asset returns",
    "Information classification",
    "Information labels",
    "Information transfer",
    "Access rules",
    "Identity lifecycle",
    "Authentication information",
    "Access entitlements",
    "Supplier security",
    "Supplier agreements",
    "Technology supply chain",
    "Supplier service reviews",
    "Cloud service security",
    "Incident preparation",
    "Event assessment",
    "Incident response",
    "Incident learning",
    "Evidence preservation",
    "Security during disruption",
    "ICT continuity",
    "Applicable obligations",
    "Intellectual property",
    "Record protection",
    "Personal information",
    "Independent security review",
    "Policy compliance",
    "Operating procedures",
  ],
  6: [
    "Personnel screening",
    "Employment terms",
    "Security education",
    "Disciplinary process",
    "Employment changes",
    "Confidentiality agreements",
    "Remote work",
    "Event reporting",
  ],
  7: [
    "Security perimeters",
    "Physical entry",
    "Protected facilities",
    "Physical monitoring",
    "Environmental threats",
    "Secure area practices",
    "Clear desks and screens",
    "Equipment protection",
    "Offsite equipment",
    "Storage media",
    "Supporting utilities",
    "Cabling protection",
    "Equipment maintenance",
    "Equipment disposal",
  ],
  8: [
    "Endpoint protection",
    "Privileged access",
    "Access restrictions",
    "Source code access",
    "Secure authentication",
    "Capacity planning",
    "Malware protection",
    "Vulnerability handling",
    "Configuration baselines",
    "Information deletion",
    "Data masking",
    "Data loss prevention",
    "Backups",
    "Redundancy",
    "Security logging",
    "Activity monitoring",
    "Clock synchronization",
    "Privileged utilities",
    "Software installation",
    "Network protection",
    "Network services",
    "Network separation",
    "Web filtering",
    "Cryptography",
    "Secure development lifecycle",
    "Application security requirements",
    "Security architecture",
    "Secure coding",
    "Security testing",
    "Outsourced development",
    "Environment separation",
    "Change control",
    "Test information",
    "Audit testing safeguards",
  ],
};
export const requirements = [
  ...[
    ["4.1", "Business context"],
    ["4.2", "Interested parties"],
    ["4.3", "ISMS boundaries"],
    ["4.4", "Management system"],
    ["5.1", "Leadership commitment"],
    ["5.2", "Management policy"],
    ["5.3", "Assigned authorities"],
    ["6.1.1", "Risks and opportunities"],
    ["6.1.2", "Risk assessment method"],
    ["6.1.3", "Risk treatment and applicability"],
    ["6.2", "Security objectives"],
    ["6.3", "Planned changes"],
    ["7.1", "Resources"],
    ["7.2", "Competence"],
    ["7.3", "Awareness"],
    ["7.4", "Communication"],
    ["7.5", "Controlled documentation"],
    ["8.1", "Operational planning"],
    ["8.2", "Risk reassessment"],
    ["8.3", "Treatment implementation"],
    ["9.1", "Performance evaluation"],
    ["9.2", "Internal audit"],
    ["9.3", "Management review"],
    ["10.1", "Continual improvement"],
    ["10.2", "Corrective action"],
  ].map(([ref, title]) => ({
    ref: `Clause ${ref}`,
    title,
    theme: "Management system",
  })),
  ...Object.entries(groups).flatMap(([group, titles]) =>
    titles.map((title, index) => ({
      ref: `A.${group}.${index + 1}`,
      title,
      theme: { 5: "Organization", 6: "People", 7: "Physical", 8: "Technology" }[
        group
      ],
    })),
  ),
];

export const guides = [
  {
    key: "scope",
    title: "Describe what you protect",
    phase: "Understand",
    why: "Your ISMS needs a clear boundary so people know which services, systems and locations are covered.",
    steps: [
      "Describe your customer-facing services and the information they use.",
      "List systems, suppliers and locations that support those services.",
      "Ask your sponsor to confirm the boundary and any exclusions.",
    ],
    evidence:
      "An approved scope statement and a current inventory of sites and services.",
    refs: ["Clause 4.1", "Clause 4.2", "Clause 4.3", "Clause 4.4"],
    template: "scope",
  },
  {
    key: "leadership",
    title: "Give security an owner",
    phase: "Understand",
    why: "Security work needs named decision-makers, funding and measurable objectives.",
    steps: [
      "Nominate a sponsor and ISMS coordinator.",
      "Assign IT, HR, facilities and supplier owners.",
      "Agree objectives and how progress will be measured.",
    ],
    evidence:
      "Approved responsibilities, objectives and management commitments.",
    refs: [
      "Clause 5.1",
      "Clause 5.2",
      "Clause 5.3",
      "Clause 6.2",
      "Clause 7.1",
      "A.5.1",
      "A.5.2",
      "A.5.3",
      "A.5.4",
    ],
    template: "policy",
  },
  {
    key: "risk",
    title: "Decide which risks matter",
    phase: "Understand",
    why: "Controls should address your actual business risks rather than become a checklist exercise.",
    steps: [
      "List critical assets, threats and business consequences.",
      "Score likelihood and impact using an agreed method.",
      "Choose treatment owners and ask authorized business owners to accept residual risks.",
      "Review the applicability of every Annex A control.",
    ],
    evidence:
      "Risk register, treatment plan and reviewed Statement of Applicability.",
    refs: [
      "Clause 6.1.1",
      "Clause 6.1.2",
      "Clause 6.1.3",
      "Clause 8.2",
      "Clause 8.3",
      "A.5.9",
    ],
    template: "risk",
  },
  {
    key: "documents",
    title: "Turn policies into daily practice",
    phase: "Implement",
    why: "A document is useful only when it describes a process people can actually follow.",
    steps: [
      "Generate a draft using your organization profile.",
      "Replace every decision placeholder with your actual process.",
      "Have an independent reviewer assess it before adoption.",
      "Assign an owner and review date.",
    ],
    evidence:
      "Approved, controlled policies and procedures with version history.",
    refs: ["Clause 6.3", "Clause 7.4", "Clause 7.5", "Clause 8.1", "A.5.37"],
    template: "document-control",
  },
  {
    key: "people",
    title: "Help everyone work securely",
    phase: "Implement",
    why: "Staff need practical guidance when joining, changing roles and leaving.",
    steps: [
      "Document onboarding and offboarding responsibilities.",
      "Run awareness training and retain attendance and quiz results.",
      "Have staff acknowledge current policy versions.",
    ],
    evidence: "Training results, acknowledgements and joiner/leaver samples.",
    refs: [
      "Clause 7.2",
      "Clause 7.3",
      "A.6.1",
      "A.6.2",
      "A.6.3",
      "A.6.4",
      "A.6.5",
      "A.6.6",
      "A.6.7",
      "A.6.8",
    ],
    template: "people",
  },
  {
    key: "access",
    title: "Check who can access your systems",
    phase: "Implement",
    why: "Old accounts and excessive privileges can expose customer information.",
    steps: [
      "List accounts and privileges in critical systems.",
      "Ask system owners to review business need.",
      "Remove inappropriate access and retain proof of the changes.",
    ],
    evidence: "Dated access review, reviewer decisions and removal tickets.",
    refs: ["A.5.15", "A.5.16", "A.5.17", "A.5.18", "A.8.2", "A.8.3", "A.8.5"],
    template: "access",
  },
  {
    key: "suppliers",
    title: "Know your critical suppliers",
    phase: "Implement",
    why: "Your suppliers can affect confidentiality, availability and customer commitments.",
    steps: [
      "List suppliers and the information/services they handle.",
      "Assess critical suppliers and record security terms.",
      "Assign recurring reviews and track outstanding issues.",
    ],
    evidence: "Supplier assessments, agreements and follow-up actions.",
    refs: ["A.5.19", "A.5.20", "A.5.21", "A.5.22", "A.5.23"],
    template: "supplier",
  },
  {
    key: "continuity",
    title: "Prove you can recover",
    phase: "Operate",
    why: "A backup alone does not demonstrate that your business can recover.",
    steps: [
      "Identify critical processes and acceptable disruption.",
      "Agree recovery time and data-loss targets.",
      "Perform a restore exercise and document measured results.",
    ],
    evidence: "BIA, continuity plan and a completed recovery test.",
    refs: ["A.5.29", "A.5.30", "A.8.13", "A.8.14"],
    template: "continuity",
  },
  {
    key: "incidents",
    title: "Practice responding to incidents",
    phase: "Operate",
    why: "People should know whom to contact and what to do before an incident happens.",
    steps: [
      "Define reporting contacts and escalation paths.",
      "Exercise a realistic scenario.",
      "Record lessons and assign improvements.",
    ],
    evidence: "Response plan, exercise or incident report and lessons learned.",
    refs: ["A.5.24", "A.5.25", "A.5.26", "A.5.27", "A.5.28"],
    template: "incident",
  },
  {
    key: "monitor",
    title: "Keep evidence current",
    phase: "Operate",
    why: "Old evidence cannot show that a control is still operating today.",
    steps: [
      "Set a recurrence for access reviews, backups and supplier reviews.",
      "Submit evidence for the requested period.",
      "Review automated alerts and resolve the underlying issue.",
    ],
    evidence: "Current accepted evidence with a clear period and owner.",
    refs: ["Clause 9.1", "A.8.8", "A.8.15", "A.8.16"],
    template: "monitoring",
  },
  {
    key: "audit",
    title: "Test your ISMS independently",
    phase: "Assure",
    why: "Independent checks identify gaps that the process owner may miss.",
    steps: [
      "Plan an audit covering the scope and applicable requirements.",
      "Assign an auditor who is independent of the work.",
      "Record findings, root causes and corrective actions.",
      "Verify action effectiveness before closure.",
    ],
    evidence: "Audit report and verified corrective-action records.",
    refs: ["Clause 9.2", "Clause 10.1", "Clause 10.2", "A.5.35", "A.5.36"],
    template: "audit",
  },
  {
    key: "review",
    title: "Bring decisions to management",
    phase: "Assure",
    why: "Management must review results and decide changes, priorities and resources.",
    steps: [
      "Gather risk, audit, objective and monitoring results.",
      "Discuss changes and outstanding actions with management.",
      "Record decisions, owners and dates.",
    ],
    evidence: "Approved management review minutes and tracked decisions.",
    refs: ["Clause 9.3"],
    template: "review",
  },
];

export const routines = [
  {
    key: "access",
    title: "Quarterly access review",
    days: 90,
    ref: "A.5.18",
    guide:
      "Export the current account list, record owner decisions and attach removal evidence.",
  },
  {
    key: "restore",
    title: "Quarterly recovery exercise",
    days: 90,
    ref: "A.8.13",
    guide:
      "Restore a representative backup and record measured recovery time and data loss.",
  },
  {
    key: "vulnerability",
    title: "Monthly vulnerability review",
    days: 30,
    ref: "A.8.8",
    guide:
      "Review current findings, prioritize remediation and document accepted exceptions.",
  },
  {
    key: "supplier",
    title: "Annual supplier reassessment",
    days: 365,
    ref: "A.5.22",
    guide:
      "Review critical suppliers, assurance reports and unresolved security concerns.",
  },
  {
    key: "training",
    title: "Annual security awareness review",
    days: 365,
    ref: "A.6.3",
    guide:
      "Reconcile training completion against the current employee population.",
  },
  {
    key: "risk",
    title: "Quarterly risk reassessment",
    days: 90,
    ref: "Clause 8.2",
    guide:
      "Review changes, new threats, treatment progress and residual risk decisions.",
  },
  {
    key: "management",
    title: "Quarterly management review",
    days: 90,
    ref: "Clause 9.3",
    guide:
      "Record performance, risk, audit results, decisions and follow-up owners.",
  },
  {
    key: "audit",
    title: "Annual internal audit",
    days: 365,
    ref: "Clause 9.2",
    guide:
      "Retain audit scope, independent auditor, sample evidence, findings and conclusions.",
  },
];

export function draftDocument(guide, profile, company) {
  const unknown = "[DECISION REQUIRED]";
  return `DRAFT — requires review and client adoption\n\n${company}: ${guide.title}\n\nService scope\n${profile.services || unknown}\n\nInformation handled\n${profile.information || unknown}\n\nAccountability\nISMS coordinator: ${profile.coordinator || unknown}\nManagement sponsor: ${profile.sponsor || unknown}\n\nPurpose\n${guide.why}\n\nRequired working arrangements\n${guide.steps.map((step, i) => `${i + 1}. ${step}\nOur process, responsible person and frequency: ${unknown}`).join("\n\n")}\n\nRecords to retain\n${guide.evidence}\nStorage location, access and retention: ${unknown}\n\nVerification\nHow we verify that this process works: ${unknown}\n\nApproval and review\nClient approver: ${profile.sponsor || unknown}\nEffective date and next review: ${unknown}\n\nReference index\n${guide.refs.join(", ")}\n\nThis guided draft is not evidence of implementation. Complete the decisions, confirm actual practice, and obtain review before publication.`;
}
