import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import express from 'express';
import request from 'supertest';
import {service,passwordHash} from './service.js';
import {newDb} from 'pg-mem';
import {pool as realPool} from './db.js';
import {createSampleClient,scopeAreas} from './sample-client.js';
import {readiness} from './readiness.js';
import {evaluateSignals} from './isms.js';

test('comprehensive sample is isolated, idempotent, covers all references and excludes reference originals from readiness',async context=>{
 let pool=realPool;
 if(process.env.TEST_REAL_DATABASE==='true')context.after(()=>pool.end());
 else {const memory=newDb();memory.public.none('CREATE TABLE tenants(id UUID PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL)');memory.public.none(await readFile(new URL('../db/service.sql',import.meta.url),'utf8'));const adapter=memory.adapters.createPg();pool=new adapter.Pool();realPool.query=pool.query.bind(pool);realPool.connect=pool.connect.bind(pool);}
 const actorId=randomUUID();await pool.query('INSERT INTO service_users VALUES($1,$2,$3,$4)',[actorId,actorId+'@sample.invalid',passwordHash('SampleTestPassword123!'),'Sample test operator']);
 const catalog=[{title:'Access policy',filename:'policy.txt',path:'source/policy.txt',text:'<<COMPANY NAME>> must record an access review. <<DECISION>>',category:'Policies',level:'Level 1',sha256:'fixture',bytes:99}];
 const sample=await createSampleClient(pool,{actorId,catalog,today:'2026-10-03'});
 assert.equal(sample.controls,118);assert.equal(sample.scopeAreas,11);assert.equal(sample.referenceFiles,1);
 const records=(await pool.query('SELECT id,kind,data FROM service_records WHERE tenant_id=$1',[sample.id])).rows;
 assert.equal(records.filter(r=>r.kind==='controls').length,118);assert.equal(records.filter(r=>r.kind==='controls'&&r.data.applicable).length,118);
 assert.equal(records.filter(r=>r.kind==='integrations'&&r.data.status!=='not_connected').length,0);
 assert.equal((await pool.query('SELECT id FROM service_sites WHERE tenant_id=$1',[sample.id])).rows.length,5);
 assert.equal((await pool.query('SELECT key FROM service_routines WHERE tenant_id=$1',[sample.id])).rows.length,8);
 const report=readiness(records,new Date('2026-10-03T12:00:00Z'));assert.equal(report.ready,111);assert.equal(report.applicable,118);
 const reference=records.find(r=>r.data.referenceOnly),control=records.find(r=>r.kind==='controls');
 reference.data={...reference.data,status:'approved',controlId:control.id,reviewedAt:'2026-10-02',expiresAt:'2027-10-03'};
 assert.equal(readiness([control,reference],new Date('2026-10-03')).ready,0);
 assert.equal(evaluateSignals([control,reference],[],{services:'test',coordinator:'A',sponsor:'B'},'2026-10-03').find(s=>s.key==='coverage').status,'attention');
 const modified=records.find(r=>r.kind==='scope');await pool.query('UPDATE service_records SET data=$1 WHERE id=$2',[{...modified.data,title:'Preserve team edits'},modified.id]);
 const repeat=await createSampleClient(pool,{actorId,catalog});assert.equal(repeat.reused,true);assert.equal(repeat.id,sample.id);
 assert.equal((await pool.query('SELECT data FROM service_records WHERE id=$1',[modified.id])).rows[0].data.title,'Preserve team edits');
 const app=express();app.use(express.json());app.use('/api',service);app.use((error,_req,res,_next)=>res.status(error.status||500).json({error:error.message}));
 const admin=request.agent(app);await admin.post('/api/login').send({email:actorId+'@sample.invalid',password:'SampleTestPassword123!'}).expect(200);
 const base='/api/workspaces/'+sample.id;
 await admin.patch(base+'/isms/profile').send({coordinator:'Updated sample coordinator'}).expect(200);const state=(await admin.get(base+'/isms').expect(200)).body;assert.equal(state.program.profile.sample,true);assert.equal(state.program.profile.scopeAreas.length,11);
 await admin.patch(base+'/records/'+reference.id).send({referenceOnly:false,status:'approved',reviewNote:'Try to approve source'}).expect(403);
 const copy=(await admin.post(base+'/isms/reference-drafts/'+reference.id).send({}).expect(201)).body.id;
 assert.equal((await admin.post(base+'/isms/reference-drafts/'+reference.id).send({}).expect(201)).body.id,copy);
 let working=(await admin.get(base+'/records').expect(200)).body.find(r=>r.id===copy);assert.equal(working.data.referenceOnly,undefined);assert.ok(working.data.description.includes('[DECISION REQUIRED]'));
 await admin.patch(base+'/records/'+copy).send({status:'approved',reviewNote:'Try unresolved copy'}).expect(400);
 await admin.patch(base+'/records/'+copy).send({description:'Completed real-process example for test validation.',controlId:control.id,expiresAt:'2099-01-01',status:'approved',reviewNote:'Process and sources reviewed'}).expect(200);
 const another=(await admin.post('/api/workspaces').send({company:'Another isolated sample-test workspace'}).expect(201)).body.id;
 await admin.post('/api/workspaces/'+another+'/isms/activate').send({}).expect(201);
 await admin.post('/api/workspaces/'+another+'/isms/reference-drafts/'+reference.id).send({}).expect(404);
 const auditorEmail=randomUUID()+'@sample.invalid';await admin.post(base+'/members').send({email:auditorEmail,password:'SampleTestPassword123!',name:'Sample test auditor',role:'auditor'}).expect(201);
 const auditor=request.agent(app);await auditor.post('/api/login').send({email:auditorEmail,password:'SampleTestPassword123!'}).expect(200);await auditor.post(base+'/isms/reference-drafts/'+reference.id).send({}).expect(403);
 assert.equal(scopeAreas.length,11);
});
