import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import express from 'express';
import request from 'supertest';
import { newDb } from 'pg-mem';
import {pool} from './db.js';
import {service} from './service.js';

test('workspace lifecycle enforces isolation and human document approval',async()=>{
 const memory=newDb();
 memory.public.none('CREATE TABLE tenants(id UUID PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL)');
 memory.public.none(await readFile(new URL('../db/service.sql',import.meta.url),'utf8'));
 const adapter=memory.adapters.createPg();const db=new adapter.Pool();pool.query=db.query.bind(db);pool.connect=db.connect.bind(db);
 const app=express();app.use(express.json());app.use('/api',service);app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));
 const admin=request.agent(app),other=request.agent(app),client=request.agent(app);
 const account={email:'owner@example.com',password:'test-password-long',name:'Owner',company:'Acme'};
 await admin.post('/api/register').send(account).expect(201);
 await admin.post('/api/login').send({...account,password:'wrong'}).expect(401);
 await admin.post('/api/login').send(account).expect(200);
 const me=(await admin.get('/api/me').expect(200)).body;const tenant=me.workspaces[0].id;const base=`/api/workspaces/${tenant}`;
 await other.post('/api/register').send({...account,email:'other@example.com',company:'Other'}).expect(201);
 await other.post('/api/login').send({...account,email:'other@example.com'}).expect(200);
 await other.get(base+'/records').expect(403);
 const records=(await admin.get(base+'/records').expect(200)).body;assert.equal(records.filter(r=>r.kind==='controls').length,12);
 await admin.post(base+'/members').send({email:'client@example.com',password:account.password,name:'Client',role:'client'}).expect(201);
 await client.post('/api/login').send({email:'client@example.com',password:account.password}).expect(200);
 const doc=(await client.post(base+'/records/documents').send({title:'Security policy',description:'approved annual',status:'approved'}).expect(201)).body;
 assert.equal(doc.data.status,'review_required');
 await client.patch(base+'/records/'+doc.id).send({status:'approved',reviewNote:'Looks good'}).expect(403);
 const file=(await client.post(base+'/upload').send({filename:'policy.txt',content:Buffer.from('Information security policy for Acme').toString('base64')}).expect(201)).body;
 const downloaded=await client.get(base+'/files/'+file.id).expect(200);assert.ok(downloaded.body.toString().includes('Information security'));
 await other.get(base+'/files/'+file.id).expect(403);
 await admin.patch(base+'/records/'+doc.id).send({status:'approved'}).expect(400);
 await admin.patch(base+'/records/'+doc.id).send({status:'approved',reviewNote:'Reviewed approval and scope',controlId:records.find(r=>r.kind==='controls').id}).expect(200);
 const exported=(await admin.get(base+'/export').expect(200)).body;assert.ok(exported.events.some(e=>e.action==='documents.updated'));
 await admin.post('/api/logout').expect(200);await admin.get('/api/me').expect(401);
});
